# Generated by Django 6.0.2 on 2026-03-01 15:32

import product_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=product_api.models.upload_location),
        ),
    ]
